---
title: "News"
author: "Eleanor Pullenayegum"
date: "September 5, 2024"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# IrregLong 0.4.0
## Major changes
* added Liangint, a function to estimate a semi-parametric joint model that includes an intercept term
* added clustered.bootstrap, a function to create a single bootstrapped dataset from data with one clustering variable

## Minor changes
* due to possible archival of the geepack package, GEEs are now estimated using geem from the geeM package
* added option (loess.stabilize) in iiw.weights to add additional stabilization to avoid time trends in the weights.


# IrregLong 0.3.4
## Minor changes
* added error message to extent.of.irregularity for when formula and/or ncutpts are not specified in the absence of scheduled visit times
* added a transformed AUC to extent.of.irregularity
* made use of data.table package when lagging variables and adding censored rows

## Bug fixes
* extent.of.irregularity previously only allowed the time variable to be called "time"; this has now been fixed

# IrregLong 0.3.3
## Minor changes
* due to archival of the frailtypack package, frailty models are now estimated using coxph rather than frailtyPenal

# IrregLong 0.3.2
## Bug fixes
* iiw.weights failed to consider the interval between last observed visit and end of follow-up time when maxfu was supplied as a single number. This has been fixed.

# IrregLong 0.3.1
## Bug fixes
* Fixed a coding error that led extent.of.irregularity to fail when scheduledtimes was provided.


# IrregLong 0.3.0

## Major changes

* Added function (extent.of.irregularity) to provide graphical and numeric summaries of the extent of irregularity.


## Minor changes

* Added an option in the Liang function to provide as an argument a function computing the value of the covariates X for any subject at any given time t, not just the observation times.


# IrregLong 0.2.0

## Major changes

* When using lagged variable, there is an option to include a value for the first lagged observation within each subject.
* A function (abacus.plot) for producing an abacus plot has been added.
* The Liang model now allows for time-invariant covariates to be included in the visit process model.


## Bug fixes

* The documentation (examples and vignette) has been updated to use dosing by weight in the measurement frequency model.
* tinvarcols can be omitted from addcensoredrows, iiwgee, and iiw.weights if maxfu=NULL.
* lagfn and addcensoredrows no longer require subject identifiers to be numeric.



